"""reset_and_fix_schema

Revision ID: ddc39f488f1e
Revises: 
Create Date: 2026-04-25 12:11:36.426208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddc39f488f1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('wells',
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=False),
    sa.Column('zone', sa.String(length=255), nullable=True),
    sa.Column('basin', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('total_depth_m', sa.Float(), nullable=True),
    sa.Column('spud_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('well_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('well_id')
    )
    op.create_index(op.f('ix_wells_code'), 'wells', ['code'], unique=True)
    op.create_index(op.f('ix_wells_field'), 'wells', ['field'], unique=False)
    op.create_index(op.f('ix_wells_name'), 'wells', ['name'], unique=False)
    op.create_index(op.f('ix_wells_well_id'), 'wells', ['well_id'], unique=False)
    op.create_index(op.f('ix_wells_zone'), 'wells', ['zone'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('result_type', sa.Enum('POROSITY', 'WATER_SATURATION', 'PERMEABILITY', 'LITHOLOGY', 'NET_PAY', 'FORMATION_EVALUATION', 'OTHER', name='resulttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('depth_from_m', sa.Float(), nullable=True),
    sa.Column('depth_to_m', sa.Float(), nullable=True),
    sa.Column('zone_name', sa.String(length=255), nullable=True),
    sa.Column('formation_name', sa.String(length=255), nullable=True),
    sa.Column('porosity_avg', sa.Float(), nullable=True),
    sa.Column('water_saturation_avg', sa.Float(), nullable=True),
    sa.Column('permeability_avg_md', sa.Float(), nullable=True),
    sa.Column('net_pay_m', sa.Float(), nullable=True),
    sa.Column('gross_pay_m', sa.Float(), nullable=True),
    sa.Column('ntg_ratio', sa.Float(), nullable=True),
    sa.Column('porosity_cutoff', sa.Float(), nullable=True),
    sa.Column('sw_cutoff', sa.Float(), nullable=True),
    sa.Column('vshale_cutoff', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=255), nullable=True),
    sa.Column('parameters_used', sa.JSON(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.well_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_results_result_type'), 'analysis_results', ['result_type'], unique=False)
    op.create_table('petrophysical_files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.Enum('LAS', 'CSV', name='filetype'), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PROCESSED', 'ERROR', name='filestatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('well_name_in_file', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('field_in_file', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('country_in_file', sa.String(length=100), nullable=True),
    sa.Column('date_in_file', sa.String(length=100), nullable=True),
    sa.Column('service_company', sa.String(length=255), nullable=True),
    sa.Column('start_depth', sa.Float(), nullable=True),
    sa.Column('stop_depth', sa.Float(), nullable=True),
    sa.Column('step', sa.Float(), nullable=True),
    sa.Column('depth_unit', sa.String(length=20), nullable=True),
    sa.Column('null_value', sa.Float(), nullable=True),
    sa.Column('available_curves', sa.JSON(), nullable=True),
    sa.Column('curve_units', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['wells.well_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_petrophysical_files_file_id'), 'petrophysical_files', ['file_id'], unique=False)
    op.create_table('curve_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('curve_name', sa.String(length=50), nullable=False),
    sa.Column('depth_m', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['petrophysical_files.file_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['well_id'], ['wells.well_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_curve_file_name', 'curve_data', ['file_id', 'curve_name'], unique=False)
    op.create_index('idx_curve_well_depth', 'curve_data', ['well_id', 'curve_name', 'depth_m'], unique=False)
    op.create_index(op.f('ix_curve_data_curve_name'), 'curve_data', ['curve_name'], unique=False)
    op.create_index(op.f('ix_curve_data_id'), 'curve_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_curve_data_id'), table_name='curve_data')
    op.drop_index(op.f('ix_curve_data_curve_name'), table_name='curve_data')
    op.drop_index('idx_curve_well_depth', table_name='curve_data')
    op.drop_index('idx_curve_file_name', table_name='curve_data')
    op.drop_table('curve_data')
    op.drop_index(op.f('ix_petrophysical_files_file_id'), table_name='petrophysical_files')
    op.drop_table('petrophysical_files')
    op.drop_index(op.f('ix_analysis_results_result_type'), table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_wells_zone'), table_name='wells')
    op.drop_index(op.f('ix_wells_well_id'), table_name='wells')
    op.drop_index(op.f('ix_wells_name'), table_name='wells')
    op.drop_index(op.f('ix_wells_field'), table_name='wells')
    op.drop_index(op.f('ix_wells_code'), table_name='wells')
    op.drop_table('wells')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
